alias bundle='$(rbenv which bundle)'
alias -g be='bundle exec'
alias -g r='rake'
alias -g ber='be r'
alias -g bre='be r'
alias -g b='bundle'
alias  rs='rails'
alias  rss='rails server'
alias  bi='bundle install --path vendor/bundle'
alias  ba='ber build:all'
alias  br='bundle exec rake'
alias  brt='br test'
alias  brr='br build:all run'
alias  bes='be bin/rails server'

